### ISSUE TITLE
Varied results between running umu-run via terminal and toml

### ISSUE THREAD

**Issue by Narfmeister** [Open-Wine-Components/ULWGL#254]
I'm attempting to launch Star Citizen via umu-run and am experiencing mixed results depending on whether I am using the terminal parameters or running via the toml config. Using the terminal parameters, I also had force STORE=none otherwise I experienced the same result as when using the toml config, but with the toml config the behaviour seems to be the same whether I specify store or leave it out.

My terminal parameters are as follows: `WINEPREFIX=$HOME/Games/star-citizen STORE=none GAMEID=umu-starcitizen PROTONPATH="$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-16" umu-run "$HOME/Games/star-citizen/drive_c/Program Files/Roberts Space Industries/RSI Launcher/RSI Launcher.exe"`

Which seems to work fine: 
https://paste.gloriouseggroll.tv/?e989ae44eb73ee3d#Avz8mwKw789etPKZUmPfUDmDEUin6bcFrenofSjwgzyS

However if a use a toml file with the following config: 
```toml
[umu]
prefix = "~/Games/star-citizen"
proton = "~/.local/share/Steam/compatibilitytools.d/GE-Proton9-16"
game_id = "umu-starcitizen"
exe = "~/Games/star-citizen/drive_c/Program Files/Roberts Space Industries/RSI Launcher/RSI Launcher.exe"
store = "none"
launch_args = []
```

It does not appear to recognise the gameid and starts without the prefix: 
https://paste.gloriouseggroll.tv/?580fd6462c8b7f30#8fLo2Jt9KubUM7WaufBbpRWvGBBamPiaAmYkMxc95bfo

I'm not entirely sure what's causing this inconsistent behaviour.
Is there something I've done wrong?
