### ISSUE TITLE
Add "Launch Options" (not `launch_args`) to the `config.toml`

### ISSUE THREAD

**Issue by Kagukara** [Open-Wine-Components/ULWGL#339]
Being able to add all your configurations to 1 file would great and what I thought the `config.toml` would allow, but it doesn't so far. 

There was this comment for a suggestion to add `[env]` for your environment variables https://github.com/Open-Wine-Components/umu-launcher/issues/135#issuecomment-2206921313 (hasn't had any activity since Jul 4, 2024) and this PR for adding `gamescope` https://github.com/Open-Wine-Components/umu-launcher/pull/179 that was closed (Oct 29, 2024).

Why not just add what Steam allows users to do with "Launch Options"? This would enable the user to add anything including environment variables and launch options to this section.

Example:
```toml
[umu]
launch_options = ["MESA_SHADER_CACHE_DIR=~/location/to/game/cache/mesa_shader", "VKD3D_SHADER_CACHE_PATH=/location/to/game/cache/vkd3d_shader", "gamemoderun", "gamescope -w 3840 -h 1800 -f"]
```
